### PR TITLE
Fixed Tile constructor for empty tiles

### LINKED ISSUE #68: Cannot construct empty Tile.
Memory size check for Tiles with either row or column size 0 is wrong.

### PR DESCRIPTION
**Pull request by rasolca**
closes #68 .

Tile constructor has been fixed for empty matrices.
Tile test has been updated to test empty matrices too.
Tile test has been improved.

### CODE REVIEW

File: test/include/dlaf_test/util_tile.h [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+/// @pre el return type should be T.
+template <class T, class Func>
+void checkEQ(Tile<T, Device::CPU>& tile, Func el, const char* file, const int line) {
+  auto comp = [](T expected, T value) { return expected == value; };
+  auto err_message = [](T expected, T value) {
+    std::stringstream s;
+    s << "expected " << expected << " == " << value;
+    return s.str();
+  };
+  internal::check(tile, el, comp, err_message, file, line);
```
Comment (albestro) [inline test/include/dlaf_test/util_tile.h]: FYI, you may use [`std::equal_to<T>{}`](https://en.cppreference.com/w/cpp/utility/functional/equal_to) instead of the custom defined lambda `comp`

File: test/include/dlaf_test/util_tile.h [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+#pragma once
+#include <sstream>
+#include "gtest/gtest.h"
+#include "dlaf/tile.h"
+
+namespace dlaf_test {
+namespace tile_test {
+using namespace dlaf;
+
+/// @brief Sets the element of the tile.
```
Comment (albestro) [inline test/include/dlaf_test/util_tile.h]: typo: *element* __s__

File: test/include/dlaf_test/util_tile.h [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+  auto err_message = [](T expected, T value) {
+    std::stringstream s;
+    s << "expected " << expected << " == " << value;
+    return s.str();
+  };
+  internal::check(tile, el, comp, err_message, file, line);
+}
+#define CHECK_TILE_EQ(el, tile) ::dlaf_test::tile_test::checkEQ(tile, el, __FILE__, __LINE__);
+
+/// @brief Checks the pointers to the elements of the matrix.
```
Comment (albestro) [inline test/include/dlaf_test/util_tile.h]: matrix -> tile ?
