### PR TITLE
Fix gtest_hpx_main

### LINKED ISSUE #64: HPX tests do not return the error code correctly.
HPX tests which use `gtest_hpx_main` always return 0 even on case of failure.

### PR DESCRIPTION
**Pull request by rasolca**
Fixes #64.

`gtest_hpx_main` now return the correct error code.
`Tile` tests which were silently failing has been fixed too.

### CODE REVIEW

File: test/src/gtest_hpx_main.cpp [hunk 1]
```diff
@@ -46,16 +46,18 @@
...
   hpx::runtime* rt = hpx::get_runtime_ptr();
   hpx::util::yield_while([rt]() { return rt->get_state() < hpx::state_running; });
 
-  hpx::threads::run_as_hpx_thread(test_main, argc, argv);
+  auto ret = hpx::threads::run_as_hpx_thread(test_main, argc, argv);
+  hpx::stop();
 
-  hpx::apply([]() { hpx::finalize(); });
-  return hpx::stop();
+  return ret;
```
Comment (albestro) [inline test/src/gtest_hpx_main.cpp]: Lookin at HPX documentation [here](https://stellar-group.github.io/hpx/docs/sphinx/latest/html/manual/starting_the_hpx_runtime.html?highlight=start#supply-your-own-main-hpx-entry-point-while-avoiding-to-block-the-main-thread) it seems that we can have just as `main` code this:

```cpp
int main() {
  // rename `test_main` to `hpx_main`, otherwise pass `&test_main` as first parameter
  hpx::start(argc, argv);
  return hpx::stop();
}
```

Am I wrong? Is there any reason why you should take care of the `hpx::runtime` like you did?

Comment (rasolca) [reply test/src/gtest_hpx_main.cpp]: To initialize HPX in the same way we will do in the library. (We cannot force to replace main in the applications).
