### PR TITLE
Fix empty cases for tridiagonal solver

### LINKED ISSUE #625: Tridiagonal solver problem with empty matrices
About empty matrices tests

https://github.com/eth-cscs/DLA-Future/blob/fa5ef85793db4de75329fa58c72a18a9fc04d8a6/test/unit/eigensolver/test_eigensolver.cpp#L52

https://github.com/eth-cscs/DLA-Future/blob/fa5ef85793db4de75329fa58c72a18a9fc04d8a6/test/unit/eigensolver/test_gen_eigensolver.cpp#L50

The problem is that here

https://github.com/eth-cscs/DLA-Future/blob/fa5ef85793db4de75329fa58c72a18a9fc04d8a6/include/dlaf/eigensolver/tridiag_solver/mc.h#L92-L98

`i_end` becomes negative when there are no tiles, i.e. with empty matrices, which is not valid for `reserve` (with DLAF_ASSERTs enabled the `to_sizet` correctly catches it).

It should be an easy fix, but probably it is even easier for you @teonnik to add the quick return in the right point of the code.

I can open an issue for that, since probably it would be better to add a test case for it in tridiagonal solver.

_Originally posted by @albestro in https://github.com/eth-cscs/DLA-Future/issues/547#issuecomment-1209186510_

### PR DESCRIPTION
**Pull request by albestro**
Fix #625

This is required by #547.

### CODE REVIEW

File: test/unit/eigensolver/test_tridiag_solver.cpp [hunk 1]
```diff
@@ -158,7 +161,7 @@ void solveRandomTridiagMatrix(SizeType n, SizeType nb) {
   std::vector<RealParam> diag_arr(to_sizet(n));
   std::vector<RealParam> offdiag_arr(to_sizet(n));
   SizeType diag_seed = n;
-  SizeType offdiag_seed = n - 1;
+  SizeType offdiag_seed = n + 1;
```
Comment (teonnik) [inline test/unit/eigensolver/test_tridiag_solver.cpp:164]: Hmm, why is this needed?

**Review by teonnik — APPROVED** [review]
LGTM overall!

File: test/unit/eigensolver/test_tridiag_solver.cpp (hunk 1 above)
Comment (albestro) [reply test/unit/eigensolver/test_tridiag_solver.cpp:164]: Because `n == 0` make `offdiag_seed = -1`, which will internally get casted to `size_t` (more generally an `unsigned int`) as it is the input seed for the random engine `std::mt19937_64`.

**Comment by albestro** [comment]
bors try
